"""Page generators — produce wiki/self/ pages from TSAL discoveries.

Every external write is dispatched through a `WikiWriterAdapter`
callable so the generators are unit-testable without the real
WikiWriteTool. Production wires `make_default_wiki_writer()` which
delegates to `app.tools.wiki_tools.WikiWriteTool`.

Seven pages, matching TSAL spec §7:
  technical-architecture / host-environment / component-inventory /
  resource-state / operating-principles / code-map / cascade-profile
"""
from __future__ import annotations

import logging
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Callable, Optional

from .self_model import TechnicalSelfModel

logger = logging.getLogger(__name__)


# Adapter signature: (slug, body, frontmatter_dict, author) -> str (path written or "")
WikiWriterAdapter = Callable[[str, str, dict, str], str]


def make_default_wiki_writer() -> WikiWriterAdapter:
    """Production adapter delegating to the existing WikiWriteTool."""
    def _writer(slug: str, body: str, fm: dict, author: str) -> str:
        try:
            from app.tools.wiki_tools import WikiWriteTool
            tool = WikiWriteTool()
            # WikiWriteTool's signature is action-based; we use update if possible
            return tool._run(
                action="update",
                section="self",
                slug=slug,
                author=author,
                title=fm.get("title", slug),
                content=body,
                confidence=fm.get("confidence", "high"),
                tags=",".join(fm.get("tags", []) or []),
                related=",".join(fm.get("related_pages", []) or []),
                source="synthesis",
            )
        except Exception as exc:
            logger.debug("tsal: wiki write failed for %s: %s", slug, exc)
            return ""
    return _writer


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _common_fm(
    slug: str, title: str, page_type: str,
    author: str, tags: list, related: Optional[list] = None,
) -> dict:
    return {
        "title": title, "slug": slug, "section": "self",
        "page_type": page_type, "epistemic_status": "factual",
        "confidence": "high", "created_by": author, "created_at": _now(),
        "updated_by": author, "updated_at": _now(),
        "tags": tags, "related_pages": related or [],
        "ownership": {"owned_by": "self", "valued_as": "high"},
        "status": "active",
    }


# ─────────────────────────────────────────────────────────────────────
# PageGenerator
# ─────────────────────────────────────────────────────────────────────

class PageGenerator:
    """Generates the seven wiki/self/ pages from a TechnicalSelfModel."""

    def __init__(self, wiki_writer: Optional[WikiWriterAdapter] = None) -> None:
        self._writer = wiki_writer or make_default_wiki_writer()

    # ── Public ──────────────────────────────────────────────────────
    def generate_all(self, model: TechnicalSelfModel) -> dict:
        """Generate every page from the model. Returns slug → wiki path."""
        return {
            "technical-architecture": self.generate_technical_architecture(model.codebase),
            "host-environment":       self.generate_host_environment(model.host),
            "component-inventory":    self.generate_component_inventory(model.components),
            "resource-state":         self.generate_resource_state(model.resources, model.host),
            "operating-principles":   self.generate_operating_principles(model.operating_principles),
            "code-map":               self.generate_code_map(model.codebase),
            "cascade-profile":        self.generate_cascade_profile(model.components.cascade),
        }

    # ── Per-page ────────────────────────────────────────────────────
    def generate_technical_architecture(self, codebase) -> str:
        body = [
            "# Technical Architecture",
            "",
            "Auto-generated by TSAL code analyst (AST parsing, not declared).",
            f"Last analyzed: {codebase.analyzed_at}",
            "",
            "## Codebase Summary",
            f"- Project root: {codebase.project_root}",
            f"- Total Python modules: {codebase.total_modules}",
            f"- Total lines of code: {codebase.total_lines:,}",
            f"- Total classes: {codebase.total_classes}",
            f"- Total registered tools: {len(codebase.tools)}",
            "",
            "## Discovered Architectural Patterns",
        ]
        for p in codebase.patterns_detected:
            body.append(f"- {p}")
        body.append("")
        body.append("## Registered Tools")
        for t in codebase.tools[:50]:
            body.append(f"- **{t.get('name')}** — {t.get('module')}")
        body.append("")
        body.append("## Agent Configuration")
        for a in codebase.agents[:20]:
            if isinstance(a, dict):
                body.append(f"- **{a.get('role', 'unknown')}**")
            else:
                body.append(f"- **{a}**")
        return self._dispatch(
            "technical-architecture", "Technical Architecture — Discovered",
            "analysis", "tsal-code-analyst",
            ["technical", "self-knowledge", "discovered"],
            ["self/host-environment", "self/component-inventory", "self/code-map"],
            "\n".join(body),
        )

    def generate_host_environment(self, host) -> str:
        body = [
            "# Host Environment",
            "",
            "Discovered through system introspection.",
            "",
            "## Hardware",
            f"- CPU: {host.cpu_model}",
            f"- Architecture: {host.cpu_architecture}",
            f"- Cores: {host.cpu_cores_physical} physical, {host.cpu_cores_logical} logical",
            f"- RAM: {host.ram_total_gb} GB"
            + (" (unified with GPU)" if host.gpu_unified_memory else ""),
            f"- GPU: {host.gpu_model}",
            f"- GPU Memory: {host.gpu_memory_gb} GB",
            f"- Disk: {host.disk_total_gb} GB total, {host.disk_available_gb} GB available",
            "",
            "## Operating System",
            f"- OS: {host.os_name} {host.os_version}",
            f"- Hostname: {host.hostname}",
            f"- Python: {host.python_version}",
            "",
            "## Capabilities",
            f"- Local LLM inference: {'Yes' if host.can_run_local_llm else 'No'}",
            f"- Estimated max local model: ~{host.max_local_model_params_b}B parameters (q4)",
            f"- GPU acceleration: {'Yes' if host.has_gpu_acceleration else 'No'}",
            f"- Metal: {'Yes' if host.metal_support else 'No'}",
            f"- CUDA: {'Yes' if host.cuda_support else 'No'}",
        ]
        return self._dispatch(
            "host-environment", "Host Environment — Discovered",
            "entity", "tsal-host-prober",
            ["technical", "hardware", "discovered"],
            ["self/resource-state", "self/cascade-profile"],
            "\n".join(body),
        )

    def generate_component_inventory(self, components) -> str:
        body = [
            "# Component Inventory",
            "",
            f"Discovered: {components.discovered_at}",
            "",
            "## Knowledge Stores",
            f"- ChromaDB: {'available' if components.chromadb.available else 'unavailable'}, "
            f"{len(components.chromadb.collections)} collections, "
            f"{components.chromadb.total_documents} documents",
            f"- Neo4j: {'available' if components.neo4j.available else 'unavailable'}, "
            f"{components.neo4j.node_count} nodes, "
            f"{components.neo4j.relation_count} relations",
            f"- Mem0 curated: {'available' if components.mem0.curated_available else 'unavailable'}",
            f"- Mem0 full: {'available' if components.mem0.full_available else 'unavailable'}",
            "",
            "## Local Inference",
            f"- Ollama: {'available' if components.ollama.available else 'unavailable'}",
            f"- Models installed: {len(components.ollama.models_installed)}",
            f"- Currently loaded: {components.ollama.model_loaded or '(none)'}",
            "",
            "## Wiki",
            f"- Total pages: {components.wiki.total_pages}",
            f"- Disk usage: {components.wiki.disk_usage_mb} MB",
            f"- Sections: {', '.join(sorted(components.wiki.pages_by_section))}",
        ]
        return self._dispatch(
            "component-inventory", "Component Inventory — Discovered",
            "analysis", "tsal-component-discovery",
            ["technical", "components", "discovered"],
            ["self/host-environment", "self/cascade-profile"],
            "\n".join(body),
        )

    def generate_resource_state(self, resources, host) -> str:
        warnings = []
        if resources.compute_pressure > 0.7:
            warnings.append("⚠ High compute pressure — defer non-critical operations")
        if resources.storage_pressure > 0.8:
            warnings.append("⚠ Low disk space — consider cleanup")
        if not warnings:
            warnings.append("✓ Resources healthy")
        body = [
            "# Resource State",
            "",
            f"## Current Utilization ({resources.probed_at})",
            f"- CPU: {resources.cpu_percent}%",
            f"- RAM: {resources.ram_used_gb}/{host.ram_total_gb} GB ({resources.ram_percent}%)",
            f"- Available for inference: {resources.available_for_inference_gb} GB",
            f"- Disk: {resources.disk_available_gb} GB free",
            f"- Compute pressure: {resources.compute_pressure:.2f}",
            f"- Storage pressure: {resources.storage_pressure:.2f}",
            "",
            "## Running Services",
            f"- Ollama: {'running' if resources.ollama_running else 'NOT running'}"
            + (f", loaded: {resources.ollama_model_loaded}" if resources.ollama_model_loaded else ""),
            f"- Neo4j: {'running' if resources.neo4j_running else 'NOT running'}",
            f"- PostgreSQL: {'running' if resources.postgresql_running else 'NOT running'}",
            "",
            "## Planning Signal",
        ] + warnings
        return self._dispatch(
            "resource-state", "Resource State — Live",
            "log-entry", "tsal-resource-monitor",
            ["technical", "resources", "live"],
            ["self/host-environment"],
            "\n".join(body),
        )

    def generate_operating_principles(self, principles_text: str) -> str:
        body = [
            "# Operating Principles",
            "",
            "Inferred from discovered architecture (Tier-1 LLM synthesis).",
            "Regenerated weekly or after significant codebase change.",
            "",
            principles_text or "_No principles inferred yet — TSAL will populate on next weekly cycle._",
        ]
        return self._dispatch(
            "operating-principles", "Operating Principles — Inferred",
            "analysis", "tsal-principles-inferer",
            ["technical", "principles", "inferred"],
            ["self/technical-architecture", "self/component-inventory"],
            "\n".join(body),
        )

    def generate_code_map(self, codebase) -> str:
        body = [
            "# Code Map",
            "",
            "Module dependency overview (from AST imports).",
            "",
            "## Packages",
        ]
        for pkg in codebase.packages:
            body.append(f"- {pkg}")
        body.append("")
        body.append("## High-fan-in modules (most imported)")
        # invert the dependency graph
        fan_in: dict[str, int] = {}
        for src, imports in codebase.dependencies.items():
            for imp in imports:
                fan_in[imp] = fan_in.get(imp, 0) + 1
        top = sorted(fan_in.items(), key=lambda kv: -kv[1])[:20]
        for name, n in top:
            body.append(f"- {name}: imported by {n} module(s)")
        return self._dispatch(
            "code-map", "Code Map — Module Dependencies",
            "analysis", "tsal-code-analyst",
            ["technical", "dependencies", "discovered"],
            ["self/technical-architecture"],
            "\n".join(body),
        )

    def generate_cascade_profile(self, cascade) -> str:
        body = [
            "# Cascade Profile",
            "",
            "Discovered LLM tier configuration.",
            "",
            f"Default tier: {cascade.current_default_tier}",
            "",
            "## Tiers",
        ]
        for t in cascade.tiers:
            body.append(
                f"- **{t['name']}** ({t['provider']} / {t['model']}) — "
                f"{'available' if t['available'] else 'UNAVAILABLE'}, "
                f"~{t['latency_estimate_ms']}ms, "
                f"${t['cost_per_1k_tokens']}/1k tokens"
            )
        return self._dispatch(
            "cascade-profile", "LLM Cascade Profile — Discovered",
            "analysis", "tsal-component-discovery",
            ["technical", "cascade", "discovered"],
            ["self/component-inventory", "self/resource-state"],
            "\n".join(body),
        )

    # ── Internal ─────────────────────────────────────────────────────
    def _dispatch(self, slug, title, page_type, author, tags, related, body) -> str:
        fm = _common_fm(slug, title, page_type, author, tags, related)
        try:
            return self._writer(slug, body, fm, author) or ""
        except Exception as exc:
            logger.debug("tsal: dispatch failed for %s: %s", slug, exc)
            return ""
