"""
app.self_improvement.consolidator — cluster + merge near-duplicate skills.

Phase 5 of the overhaul. Runs weekly from idle_scheduler. Also exposes a
one-shot `cleanup_existing_skills()` for compressing the 223 legacy skills
generated by the broken pre-overhaul loop.

Algorithm:
    1. Pull all active SkillRecords per KB + fetch their embeddings.
    2. Greedy cosine-threshold clustering (simpler than HDBSCAN, sufficient
       for our scale — we have hundreds of skills, not millions).
    3. For each cluster of size ≥ _MIN_CLUSTER_SIZE with median pairwise
       distance ≤ _MERGE_DISTANCE_THRESHOLD:
           - Tight (dist ≤ _AUTO_MERGE_DISTANCE): auto-merge via Writer crew
             dispatch — high-usage skill in the cluster becomes the canonical
             target; others get `status=superseded, superseded_by=canonical_id`.
           - Loose: record a ConsolidationProposal; operator can review later.

Design notes:
    - Never delete. Superseded records keep their content; chronicle/history
      invariant from CLAUDE.md. Disk mirror regen skips superseded by default.
    - The "canonical" skill in each cluster is chosen by max usage_count,
      breaking ties with earliest created_at (preserves provenance).
    - Writer-crew dispatch is deferred to Phase 6 observability — for now,
      the consolidator proposes and soft-merges via status flip.

IMMUTABLE — infrastructure-level module.
"""

from __future__ import annotations

import json
import logging
import math
from collections import defaultdict
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Optional

from app.self_improvement.types import SkillRecord

logger = logging.getLogger(__name__)


# ── IMMUTABLE: clustering thresholds ─────────────────────────────────────────
#
# Distances are cosine (0 = identical, ~1.0 = orthogonal).
# Calibrated to the same thresholds the Novelty Gate uses so decisions agree.

_MIN_CLUSTER_SIZE = 3
_MERGE_DISTANCE_THRESHOLD = 0.35      # cluster "tight enough to merge"
_AUTO_MERGE_DISTANCE = 0.20           # tight enough to merge without review

# Consolidation proposals collection — persisted so the Phase 6 dashboard
# can surface them for operator review.
_PROPOSALS_COLLECTION = "consolidation_proposals"


# ── Data type ────────────────────────────────────────────────────────────────

@dataclass
class ConsolidationProposal:
    id: str
    kb: str
    canonical_id: str              # the winner
    member_ids: list[str]          # everyone in the cluster (incl. canonical)
    size: int
    mean_distance: float
    auto_merged: bool              # True if auto-merge threshold was met
    created_at: str
    notes: str = ""

    def to_dict(self) -> dict:
        return {
            "id": self.id, "kb": self.kb, "canonical_id": self.canonical_id,
            "member_ids": self.member_ids, "size": self.size,
            "mean_distance": self.mean_distance, "auto_merged": self.auto_merged,
            "created_at": self.created_at, "notes": self.notes,
        }


# ── Embedding helpers ────────────────────────────────────────────────────────

def _get_record_embedding(record: SkillRecord) -> Optional[list[float]]:
    """Fetch the stored embedding for a record from its KB.

    All four KBs are ChromaDB collections; include=["embeddings"] retrieves
    them without recomputing. Returns None if not found.
    """
    kb = record.kb
    try:
        if kb == "episteme":
            from app.episteme.vectorstore import get_store
            col = get_store()._collection
        elif kb == "experiential":
            from app.experiential.vectorstore import get_store
            col = get_store()._collection
        elif kb == "aesthetics":
            from app.aesthetics.vectorstore import get_store
            col = get_store()._collection
        elif kb == "tensions":
            from app.tensions.vectorstore import get_store
            col = get_store()._collection
        else:
            return None
        r = col.get(ids=[record.id], include=["embeddings"])
        embs = r.get("embeddings")
        # Chroma returns numpy arrays — can't use bool truthiness on them.
        # Need explicit None and length checks.
        if embs is None:
            return None
        try:
            if len(embs) == 0:
                return None
        except TypeError:
            return None
        first = embs[0]
        if first is None:
            return None
        # Convert numpy array (or list) to plain list of floats
        try:
            return [float(x) for x in first]
        except Exception:
            return None
    except Exception:
        logger.debug(f"_get_record_embedding[{record.id}] failed", exc_info=True)
    return None


def _cosine_distance(a: list[float], b: list[float]) -> float:
    """Cosine distance in [0, 2]. 0 = identical direction."""
    if not a or not b or len(a) != len(b):
        return 2.0
    dot = sum(ai * bi for ai, bi in zip(a, b))
    na = math.sqrt(sum(ai * ai for ai in a))
    nb = math.sqrt(sum(bi * bi for bi in b))
    if na == 0 or nb == 0:
        return 2.0
    cosine_sim = dot / (na * nb)
    return max(0.0, 1.0 - cosine_sim)


# ── Clustering ───────────────────────────────────────────────────────────────

def _cluster_records(
    records: list[SkillRecord],
    threshold: float = _MERGE_DISTANCE_THRESHOLD,
) -> list[list[SkillRecord]]:
    """Complete-linkage cosine-threshold agglomerative clustering.

    For each record, join the BEST-matching cluster where the candidate's
    distance to EVERY member of the cluster is ≤ threshold (complete-link).
    This prevents the "black hole" effect where a loose centroid absorbs
    the entire collection.

    Among qualifying clusters, picks the one with the smallest max distance
    to the candidate (tightest fit).

    Simple, deterministic, O(n * c * k) where c = clusters, k = avg cluster
    size. Good enough for hundreds of records.
    """
    # Fetch embeddings upfront
    with_emb = []
    for rec in records:
        emb = _get_record_embedding(rec)
        if emb:
            with_emb.append((rec, emb))

    if not with_emb:
        return []

    clusters: list[list[tuple]] = []  # each: list of (record, emb)

    for rec, emb in with_emb:
        best_cluster_idx = -1
        best_max_dist = float("inf")

        for ci, cluster in enumerate(clusters):
            # Complete linkage: max distance to any member must be ≤ threshold
            max_dist = max(_cosine_distance(emb, e) for _, e in cluster)
            if max_dist <= threshold and max_dist < best_max_dist:
                best_cluster_idx = ci
                best_max_dist = max_dist

        if best_cluster_idx >= 0:
            clusters[best_cluster_idx].append((rec, emb))
        else:
            clusters.append([(rec, emb)])

    # Return only the records, dropped embeddings (they were only for clustering)
    return [[r for r, _ in c] for c in clusters]


def _cluster_centroid(embeddings: list[list[float]]) -> list[float]:
    if not embeddings:
        return []
    n = len(embeddings)
    dim = len(embeddings[0])
    return [sum(e[i] for e in embeddings) / n for i in range(dim)]


def _mean_pairwise_distance(records: list[SkillRecord]) -> float:
    """Mean pairwise cosine distance within a cluster. Used to gate auto-merge."""
    embs = [_get_record_embedding(r) for r in records]
    embs = [e for e in embs if e]
    if len(embs) < 2:
        return 0.0
    dists = []
    for i in range(len(embs)):
        for j in range(i + 1, len(embs)):
            dists.append(_cosine_distance(embs[i], embs[j]))
    return sum(dists) / len(dists) if dists else 0.0


def _pick_canonical(records: list[SkillRecord]) -> SkillRecord:
    """Pick the cluster winner: highest usage_count, earliest created_at as tie."""
    return max(
        records,
        key=lambda r: (r.usage_count, -_parse_iso(r.created_at)),
    )


def _parse_iso(s: str) -> float:
    if not s:
        return 0.0
    try:
        return datetime.fromisoformat(s).timestamp()
    except Exception:
        return 0.0


# ── Proposal persistence ─────────────────────────────────────────────────────

def _proposals_collection():
    try:
        from app.memory.chromadb_manager import get_client
        client = get_client()
        return client.get_or_create_collection(
            _PROPOSALS_COLLECTION, metadata={"hnsw:space": "cosine"},
        )
    except Exception:
        return None


def _persist_proposal(p: ConsolidationProposal) -> bool:
    col = _proposals_collection()
    if col is None:
        return False
    try:
        doc = json.dumps(p.to_dict())
        from app.memory.chromadb_manager import embed
        col.upsert(
            ids=[p.id],
            documents=[doc],
            metadatas=[{
                "kb": p.kb, "size": p.size, "auto_merged": bool(p.auto_merged),
                "canonical_id": p.canonical_id, "created_at": p.created_at,
            }],
            embeddings=[embed(doc)],
        )
        return True
    except Exception:
        return False


def list_proposals(limit: int = 20, auto_merged: Optional[bool] = None) -> list[dict]:
    """Return recent proposals (raw dicts so the dashboard can render directly)."""
    col = _proposals_collection()
    if col is None:
        return []
    try:
        where = {"auto_merged": bool(auto_merged)} if auto_merged is not None else None
        r = col.get(where=where, limit=limit) if where else col.get(limit=limit)
        out = []
        for doc in r.get("documents", []):
            try:
                out.append(json.loads(doc))
            except Exception:
                continue
        out.sort(key=lambda p: p.get("created_at", ""), reverse=True)
        return out
    except Exception:
        return []


# ── Main entry points ────────────────────────────────────────────────────────

def run_consolidation_cycle(
    auto_merge: bool = True,
    dry_run: bool = False,
) -> dict:
    """Full consolidation sweep across all KBs.

    Args:
        auto_merge: if True, clusters with mean_distance ≤ _AUTO_MERGE_DISTANCE
                    are merged immediately (soft — old records get
                    status=superseded, content preserved). If False,
                    everything is proposed-only.
        dry_run:    compute clusters + proposals but don't persist.

    Returns:
        {kbs: [per-kb summary], total_proposals, auto_merged}
    """
    try:
        from app.self_improvement.integrator import list_records, update_record, KB_CHOICES
    except Exception:
        return {"error": "integrator unavailable"}

    summary = {
        "kbs": [],
        "total_proposals": 0,
        "auto_merged": 0,
        "timestamp": datetime.now(timezone.utc).isoformat(timespec="seconds"),
    }

    for kb in KB_CHOICES:
        try:
            records = list_records(kb=kb, status="active", limit=2000)
            if len(records) < _MIN_CLUSTER_SIZE:
                continue

            clusters = _cluster_records(records)
            kb_summary = {
                "kb": kb, "total_active": len(records),
                "clusters": len(clusters), "mergeable_clusters": 0,
                "proposals_made": 0, "auto_merged": 0,
            }

            for cluster in clusters:
                if len(cluster) < _MIN_CLUSTER_SIZE:
                    continue
                mean_dist = _mean_pairwise_distance(cluster)
                if mean_dist > _MERGE_DISTANCE_THRESHOLD:
                    continue
                kb_summary["mergeable_clusters"] += 1

                canonical = _pick_canonical(cluster)
                others = [r for r in cluster if r.id != canonical.id]
                should_auto = auto_merge and mean_dist <= _AUTO_MERGE_DISTANCE

                import hashlib as _h
                proposal_id = (
                    f"consol_{kb}_"
                    f"{_h.sha256((canonical.id + str(len(cluster))).encode()).hexdigest()[:12]}"
                )
                prop = ConsolidationProposal(
                    id=proposal_id, kb=kb,
                    canonical_id=canonical.id,
                    member_ids=[r.id for r in cluster],
                    size=len(cluster),
                    mean_distance=round(mean_dist, 4),
                    auto_merged=should_auto,
                    created_at=datetime.now(timezone.utc).isoformat(timespec="seconds"),
                    notes=(
                        f"canonical={canonical.topic[:80]!r} "
                        f"usage={canonical.usage_count}"
                    ),
                )

                if dry_run:
                    summary["total_proposals"] += 1
                    kb_summary["proposals_made"] += 1
                    continue

                # Persist the proposal record regardless (useful audit trail)
                _persist_proposal(prop)
                summary["total_proposals"] += 1
                kb_summary["proposals_made"] += 1

                # Auto-merge: flip status on the losers
                if should_auto:
                    merged = 0
                    for r in others:
                        try:
                            r.status = "superseded"
                            r.superseded_by = canonical.id
                            update_record(r)
                            merged += 1
                        except Exception:
                            logger.debug(f"consolidate: supersede {r.id} failed",
                                         exc_info=True)
                    summary["auto_merged"] += merged
                    kb_summary["auto_merged"] += merged
                    logger.info(
                        f"consolidator[{kb}]: merged {merged} into {canonical.id} "
                        f"(mean_dist={mean_dist:.3f})"
                    )

            summary["kbs"].append(kb_summary)
        except Exception:
            logger.debug(f"consolidation_cycle[{kb}] failed", exc_info=True)

    if summary["total_proposals"]:
        logger.info(
            f"Consolidator: {summary['total_proposals']} proposal(s), "
            f"{summary['auto_merged']} auto-merged"
        )
    return summary


# ── Legacy skill migration (one-shot) ────────────────────────────────────────

def recover_from_team_shared(
    default_kb: str = "episteme",
    dry_run: bool = True,
    min_content_len: int = 200,
) -> dict:
    """Recover skill content from the legacy `team_shared` ChromaDB collection.

    Before the overhaul, the self-improvement crew stored skill summaries in
    `team_shared` alongside the raw .md writes. When the skills/*.md mirror
    was cleared during Phase 3 bringup, summary content remained recoverable
    here.

    This function walks `team_shared`, filters out reflections / self-reports
    (which are NOT skills), and pushes the rest through the Integrator.
    Novelty gate still applies — duplicates among the recovered content
    get rejected automatically.

    Args:
        default_kb: KB destination when the classifier is unsure
        dry_run:    preview counts without writing
        min_content_len: skip entries below this length (noise floor)

    Returns report dict.
    """
    import json as _json
    try:
        from app.memory.chromadb_manager import get_client
        from app.self_improvement.types import SkillDraft
        from app.self_improvement.integrator import integrate
        from app.self_improvement.novelty import novelty_report
    except Exception as exc:
        return {"error": str(exc)}

    report = {
        "total_scanned": 0, "skill_candidates": 0,
        "integrated": 0, "rejected_dup": 0, "rejected_short": 0,
        "dry_run": dry_run,
    }

    try:
        client = get_client()
        col = client.get_or_create_collection("team_shared")
    except Exception as exc:
        return {"error": f"team_shared unavailable: {exc}"}

    # CRITICAL: exclude team_shared from the novelty check during recovery.
    # The source content IS team_shared — checking novelty against it would
    # return 100% duplicates (every entry finds itself). We want to check
    # whether the NEW KBs already hold this knowledge.
    _recovery_kbs = [
        "episteme_research", "experiential_journal",
        "aesthetic_patterns", "unresolved_tensions",
    ]

    try:
        n = col.count()
    except Exception:
        n = 0
    if not n:
        return report

    # Pull in chunks to avoid loading all at once
    CHUNK = 100
    offset = 0
    import uuid as _uuid
    while offset < n:
        try:
            got = col.get(limit=CHUNK, offset=offset,
                          include=["documents", "metadatas"])
        except Exception:
            break
        docs = got.get("documents", []) or []
        metas = got.get("metadatas", []) or []
        if not docs:
            break

        for doc, meta in zip(docs, metas):
            report["total_scanned"] += 1
            meta = meta or {}

            # Filter out reflection entries: they're JSON blobs with a
            # 'went_well' / 'went_wrong' shape — not skill content.
            if meta.get("type") in ("reflection", "self_report", "prediction"):
                continue
            try:
                parsed = _json.loads(doc) if doc.startswith("{") else None
                if parsed and isinstance(parsed, dict) and (
                    "went_well" in parsed or "went_wrong" in parsed
                    or "confidence" in parsed
                ):
                    continue
            except Exception:
                pass

            # Only treat prose-like content (min length + markdown-ish)
            if len(doc) < min_content_len:
                report["rejected_short"] += 1
                continue

            report["skill_candidates"] += 1

            if dry_run:
                try:
                    rep = novelty_report(doc, kbs=_recovery_kbs)
                    if rep.is_duplicate:
                        report["rejected_dup"] += 1
                    else:
                        report["integrated"] += 1
                except Exception:
                    report["integrated"] += 1
                continue

            # Derive a topic from the first heading or first line
            first_line = doc.strip().splitlines()[0] if doc.strip() else ""
            topic = first_line.lstrip("# ").strip()[:120] or "recovered skill"

            draft = SkillDraft(
                id=f"draft_recover_{_uuid.uuid4().hex[:12]}",
                topic=topic,
                rationale="Recovered from legacy team_shared collection",
                content_markdown=doc,
                proposed_kb=default_kb,
            )
            # Exclude team_shared from novelty — the source content IS there
            result = integrate(draft, novelty_kbs=_recovery_kbs)
            if result is None:
                report["rejected_dup"] += 1
            else:
                report["integrated"] += 1

        offset += CHUNK

    logger.info(
        f"recover_from_team_shared: scanned {report['total_scanned']}, "
        f"candidates {report['skill_candidates']}, "
        f"integrated {report['integrated']}, rejected_dup {report['rejected_dup']} "
        f"(dry_run={dry_run})"
    )
    return report


def migrate_legacy_skills(
    skills_dir: str = "/app/workspace/skills",
    dry_run: bool = True,
    default_kb: str = "episteme",
) -> dict:
    """One-shot: ingest the legacy workspace/skills/*.md files into the KBs.

    Reads each .md file, classifies it via the Integrator's classifier,
    wraps it as a SkillDraft, and pushes through integrate() (which applies
    novelty check — expected to reject many of the 33 rapid_ecological_*
    siblings as near-duplicates, which is the goal).

    With dry_run=True (default), just reports what would happen. Operator
    flips to dry_run=False to execute.
    """
    from pathlib import Path
    import uuid
    try:
        from app.self_improvement.types import SkillDraft
        from app.self_improvement.integrator import integrate
        from app.self_improvement.novelty import novelty_report
    except Exception as exc:
        return {"error": str(exc)}

    path = Path(skills_dir)
    if not path.exists():
        return {"error": f"{skills_dir} not found"}

    skip = {"learning_queue.md", "README.md"}
    files = [f for f in path.glob("*.md") if f.name not in skip]

    report = {
        "total_files": len(files),
        "processed": 0, "integrated": 0, "rejected_dup": 0, "errors": 0,
        "dry_run": dry_run,
    }

    for f in files:
        try:
            content = f.read_text(encoding="utf-8").strip()
            if len(content) < 80:
                report["errors"] += 1
                continue
            topic = f.stem.replace("_", " ").strip()
            report["processed"] += 1

            if dry_run:
                rep = novelty_report(content)
                if rep.is_duplicate:
                    report["rejected_dup"] += 1
                else:
                    report["integrated"] += 1
                continue

            draft = SkillDraft(
                id=f"draft_legacy_{uuid.uuid4().hex[:12]}",
                topic=topic,
                rationale=f"Legacy migration of {f.name}",
                content_markdown=content,
                proposed_kb=default_kb,
            )
            result = integrate(draft)
            if result is None:
                report["rejected_dup"] += 1
            else:
                report["integrated"] += 1
        except Exception:
            report["errors"] += 1
            logger.debug(f"migrate_legacy_skills: {f.name} failed", exc_info=True)

    logger.info(
        f"migrate_legacy_skills: {report['integrated']} integrated, "
        f"{report['rejected_dup']} rejected as duplicates "
        f"(dry_run={dry_run})"
    )
    return report
