import { Link, useParams } from 'react-router-dom';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { useForgeToolQuery } from '../api/forge';
import { Skeleton } from './ui/Skeleton';
import { ErrorPanel } from './ui/ErrorPanel';
import {
  AuditFindings,
  AuditLogTimeline,
} from './forge/AuditTimeline';
import { CodeViewer } from './forge/CodeViewer';
import { InvocationsList } from './forge/InvocationsList';
import { InvokePanel } from './forge/InvokePanel';
import { KillPanel } from './forge/KillPanel';
import { PromotePanel } from './forge/PromotePanel';
import { SecurityEvalCard } from './forge/SecurityEvalCard';
import {
  CapabilityChip,
  RiskBadge,
  StatusBadge,
} from './forge/StatusBadge';

export function ForgeToolDetailPage() {
  const { id } = useParams<{ id: string }>();
  const { data, isLoading, error } = useForgeToolQuery(id);

  if (isLoading || !data) {
    return (
      <div className="space-y-3">
        <Skeleton className="h-10" />
        <Skeleton className="h-32" />
        <Skeleton className="h-64" />
      </div>
    );
  }

  if (error) {
    return <ErrorPanel error={error} />;
  }

  const { tool, invocations, audit_log } = data;
  const generator = tool.generator_metadata || tool.manifest?.generator;
  const declaredCaps = tool.manifest?.capabilities || [];
  const lang = tool.source_type === 'declarative' ? 'json' : 'python';

  return (
    <div className="space-y-5">
      {/* Header */}
      <div>
        <Link
          to="/forge"
          className="text-xs text-[#7a8599] hover:text-[#60a5fa]"
        >
          ← Back to Forge
        </Link>
        <div className="flex items-start justify-between gap-3 mt-2">
          <div className="min-w-0">
            <h1 className="text-xl font-semibold text-[#e2e8f0]">{tool.name}</h1>
            <div className="flex items-center gap-2 mt-1.5 flex-wrap">
              <StatusBadge status={tool.status} />
              <RiskBadge score={tool.risk_score} />
              <span className="text-xs font-mono text-[#7a8599]">
                v{tool.version} · {tool.source_type}
              </span>
              <span className="text-[10px] font-mono text-[#7a8599] truncate">
                {tool.tool_id}
              </span>
            </div>
            {tool.description && (
              <p className="text-sm text-[#cbd5e1] mt-2">{tool.description}</p>
            )}
            {tool.killed_reason && (
              <div className="mt-2 px-3 py-2 rounded bg-[#f87171]/10 border border-[#f87171]/30 text-sm text-[#f87171]">
                Killed: {tool.killed_reason}
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Summary — plain-language description, generated independently of the LLM judge */}
      {tool.summary && (
        <section className="p-5 rounded-lg border border-[#1e2738] bg-[#111820]">
          <div className="flex items-center justify-between mb-3">
            <h3 className="text-sm font-semibold text-[#e2e8f0]">Summary</h3>
            <span
              className={`text-[10px] uppercase tracking-wider px-2 py-0.5 rounded border ${
                tool.summary_source === 'llm'
                  ? 'bg-[#34d399]/10 text-[#34d399] border-[#34d399]/30'
                  : 'bg-[#7a8599]/10 text-[#7a8599] border-[#7a8599]/30'
              }`}
              title={
                tool.summary_source === 'llm'
                  ? 'Generated by the configured LLM at registration time'
                  : 'Deterministic fallback synthesised from manifest + AST when the LLM was unavailable'
              }
            >
              {tool.summary_source === 'llm' ? 'LLM' : 'deterministic'}
            </span>
          </div>
          <div className="prose prose-sm prose-invert max-w-none text-[#e2e8f0] leading-relaxed [&_code]:bg-[#0a0e14] [&_code]:px-1.5 [&_code]:py-0.5 [&_code]:rounded [&_code]:text-[#fbbf24] [&_strong]:text-[#e2e8f0] [&_p]:my-2 [&_ul]:my-2 [&_ul]:list-disc [&_ul]:pl-5 [&_li]:my-0.5 [&_pre]:bg-[#0a0e14] [&_pre]:p-3 [&_pre]:rounded [&_pre]:border [&_pre]:border-[#1e2738] [&_pre>code]:bg-transparent [&_pre>code]:p-0">
            <ReactMarkdown remarkPlugins={[remarkGfm]}>
              {tool.summary}
            </ReactMarkdown>
          </div>
        </section>
      )}

      {/* Provenance */}
      {generator && (
        <section className="p-4 rounded-lg border border-[#1e2738] bg-[#111820]">
          <h3 className="text-sm font-semibold text-[#e2e8f0] mb-3">
            Provenance
          </h3>
          <dl className="grid grid-cols-1 md:grid-cols-2 gap-3 text-xs">
            <ProvenanceRow label="Author agent" value={generator.agent} />
            <ProvenanceRow label="Generator model" value={generator.model} />
            <ProvenanceRow label="Crew run" value={generator.crew_run_id || '—'} />
            <ProvenanceRow
              label="Originating request hash"
              value={generator.originating_request_hash || '—'}
              mono
            />
            <ProvenanceRow
              label="Created"
              value={new Date(tool.created_at).toLocaleString()}
            />
            <ProvenanceRow
              label="Status changed"
              value={new Date(tool.status_changed_at).toLocaleString()}
            />
            {generator.parent_skill_ids?.length > 0 && (
              <ProvenanceRow
                label="Parent skills"
                value={generator.parent_skill_ids.join(', ')}
              />
            )}
            {tool.parent_tool_id && (
              <ProvenanceRow
                label="Parent tool"
                value={tool.parent_tool_id}
                mono
              />
            )}
          </dl>
          {generator.originating_request_text && (
            <div className="mt-4 pt-4 border-t border-[#1e2738]">
              <div className="text-xs uppercase tracking-wider text-[#7a8599] mb-1.5">
                Originating request
              </div>
              <p className="text-sm text-[#cbd5e1] whitespace-pre-wrap">
                {generator.originating_request_text}
              </p>
            </div>
          )}
        </section>
      )}

      {/* Manifest summary */}
      <section className="p-4 rounded-lg border border-[#1e2738] bg-[#111820]">
        <h3 className="text-sm font-semibold text-[#e2e8f0] mb-3">Manifest</h3>
        <div className="space-y-3">
          <div>
            <div className="text-xs uppercase tracking-wider text-[#7a8599] mb-1.5">
              Declared capabilities
            </div>
            <div className="flex flex-wrap gap-1.5">
              {declaredCaps.length > 0 ? (
                declaredCaps.map((c) => <CapabilityChip key={c} cap={c} />)
              ) : (
                <span className="text-xs text-[#7a8599]">none</span>
              )}
            </div>
          </div>
          {tool.manifest?.domain_allowlist?.length > 0 && (
            <div>
              <div className="text-xs uppercase tracking-wider text-[#7a8599] mb-1.5">
                Domain allowlist
              </div>
              <div className="flex flex-wrap gap-1.5">
                {tool.manifest.domain_allowlist.map((d) => (
                  <span
                    key={d}
                    className="px-2 py-0.5 rounded text-xs font-mono bg-[#0a0e14] border border-[#1e2738] text-[#cbd5e1]"
                  >
                    {d}
                  </span>
                ))}
              </div>
            </div>
          )}
        </div>
      </section>

      {/* Security eval — the "deep description" */}
      <SecurityEvalCard evalData={tool.security_eval as never} />

      {/* Source code */}
      <section className="p-4 rounded-lg border border-[#1e2738] bg-[#111820]">
        <h3 className="text-sm font-semibold text-[#e2e8f0] mb-3">Source</h3>
        <CodeViewer code={tool.source_code || ''} language={lang} />
      </section>

      {/* Audit findings */}
      <section className="p-4 rounded-lg border border-[#1e2738] bg-[#111820]">
        <h3 className="text-sm font-semibold text-[#e2e8f0] mb-3">
          Audit findings
        </h3>
        <AuditFindings findings={tool.audit_results || []} />
      </section>

      {/* Audit log */}
      <section className="p-4 rounded-lg border border-[#1e2738] bg-[#111820]">
        <h3 className="text-sm font-semibold text-[#e2e8f0] mb-3">
          Audit log (hash-chained)
        </h3>
        <AuditLogTimeline entries={audit_log} />
      </section>

      {/* Invoke */}
      <InvokePanel
        toolId={tool.tool_id}
        status={tool.status}
        parameterSchema={tool.manifest?.parameters || {}}
      />

      {/* Promotion */}
      <PromotePanel toolId={tool.tool_id} status={tool.status} />

      {/* Invocations */}
      <section className="p-4 rounded-lg border border-[#1e2738] bg-[#111820]">
        <h3 className="text-sm font-semibold text-[#e2e8f0] mb-3">
          Invocations
        </h3>
        <InvocationsList invocations={invocations} />
      </section>

      {/* Kill panel */}
      <KillPanel toolId={tool.tool_id} status={tool.status} />
    </div>
  );
}

function ProvenanceRow({
  label,
  value,
  mono,
}: {
  label: string;
  value: string;
  mono?: boolean;
}) {
  return (
    <div>
      <dt className="text-[#7a8599] uppercase tracking-wider text-[10px] mb-0.5">
        {label}
      </dt>
      <dd
        className={`text-[#e2e8f0] ${mono ? 'font-mono text-xs' : 'text-sm'} truncate`}
      >
        {value}
      </dd>
    </div>
  );
}
